dependencies:
  - aragon/aragonOS@4.4.0
  - OpenZeppelin/openzeppelin-contracts@2.0.0
  - GNSPS/solidity-bytes-utils@0.0.6

compiler:
  solc:
    version: 0.4.24
    optimizer:
      enabled: true
      runs: 200

networks:
  default: development
